<#
  Package a "click to use" portable realtime folder:
  - rvc_sdk_ort_realtime.exe + runtime DLLs
  - models/ (content_encoder.onnx, synthesizer.onnx, index, optional rmvpe.onnx)
  - rvc_realtime.ini (so the exe can be launched without CLI args)

  Note:
  - This does NOT commit or download any model files.
  - It only copies from paths you provide.

  Example:
    powershell -ExecutionPolicy Bypass -File scripts/package_rvc_realtime_portable.ps1 `
      -Runtime cuda `
      -Enc "E:\\RVC_models\\test-rvc-onnx\\vec-768-layer-12.onnx" `
      -Syn "E:\\RVC_models\\YaeMiko\\bachongshenzi_synthesizer.onnx" `
      -Index "E:\\RVC_models\\YaeMiko\\added_IVF256_Flat_nprobe_1_bachongshenzi_v2.index" `
      -Rmvpe "E:\\RVC_models\\test-rvc-onnx\\rmvpe.onnx" `
      -CapId 1 -PbId 2
#>

param(
  [ValidateSet("cuda", "dml")]
  [string]$Runtime = "cuda",

  [Parameter(Mandatory = $true)]
  [string]$Enc,
  [Parameter(Mandatory = $true)]
  [string]$Syn,
  [Parameter(Mandatory = $true)]
  [string]$Index,
  [string]$Rmvpe = "",

  [int]$CapId = -1,
  [int]$PbId = -1,

  # 下面这些给你默认填成“你当前验证最好用”的那套参数；需要的话可以覆盖。
  [int]$IoSr = 48000,
  [int]$ModelSr = 40000,
  [float]$BlockSec = 0.25,
  [float]$ExtraSec = 0.2,
  [float]$CrossfadeSec = 0.05,
  [int]$PrefillBlocks = 1,
  [float]$IndexRate = 0.1,
  [int]$UpKey = 6,
  [int]$Threads = 8,
  [float]$NoiseScale = 0.2,
  [float]$RmsMixRate = 1.0,
  [float]$RmvpeThreshold = 0.03,
  [float]$VadRms = 0.02,
  [float]$VadFloor = 1.0,
  [float]$MaxQueueSec = 0.3,

  [string]$OutRoot = "dist_realtime_portable"
)

$ErrorActionPreference = "Stop"

function Ensure-File([string]$Path) {
  if (!(Test-Path -LiteralPath $Path)) {
    throw "File not found: $Path"
  }
}

Ensure-File $Enc
Ensure-File $Syn
Ensure-File $Index
if ($Rmvpe -ne "") { Ensure-File $Rmvpe }

$buildDir = if ($Runtime -eq "cuda") { "build_rvc_sdk_ort/Release" } else { "build_rvc_sdk_ort/Release_dml" }
if (!(Test-Path $buildDir)) {
  throw "Build output not found: $buildDir (run scripts/build_rvc_sdk_ort.ps1 first)."
}

$outDir = Join-Path $OutRoot "win-x64-$Runtime"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

# Copy binaries + runtime DLLs (reuse existing packaging logic conceptually, but keep output minimal).
Copy-Item -Force -Path "$buildDir/rvc_sdk_ort_realtime.exe" -Destination "$outDir/"
Copy-Item -Force -Path "$buildDir/rvc_sdk_ort.dll" -Destination "$outDir/"

Copy-Item -Force -Path "$buildDir/onnxruntime.dll" -Destination "$outDir/" -ErrorAction SilentlyContinue
Copy-Item -Force -Path "$buildDir/DirectML.dll" -Destination "$outDir/" -ErrorAction SilentlyContinue
Copy-Item -Force -Path "$buildDir/onnxruntime_providers_cuda.dll" -Destination "$outDir/" -ErrorAction SilentlyContinue
Copy-Item -Force -Path "$buildDir/onnxruntime_providers_shared.dll" -Destination "$outDir/" -ErrorAction SilentlyContinue

Copy-Item -Force -Path "$buildDir/faiss.dll" -Destination "$outDir/" -ErrorAction SilentlyContinue
Copy-Item -Force -Path "$buildDir/libblas.dll" -Destination "$outDir/" -ErrorAction SilentlyContinue
Copy-Item -Force -Path "$buildDir/liblapack.dll" -Destination "$outDir/" -ErrorAction SilentlyContinue

# Models
$modelsDir = Join-Path $outDir "models"
New-Item -ItemType Directory -Force -Path $modelsDir | Out-Null
Copy-Item -Force -Path $Enc -Destination (Join-Path $modelsDir "content_encoder.onnx")
Copy-Item -Force -Path $Syn -Destination (Join-Path $modelsDir "synthesizer.onnx")
Copy-Item -Force -Path $Index -Destination (Join-Path $modelsDir "retrieval.index")
if ($Rmvpe -ne "") {
  Copy-Item -Force -Path $Rmvpe -Destination (Join-Path $modelsDir "rmvpe.onnx")
}

# INI config (exe will auto load this when args are omitted)
$ini = @"
; rvc_realtime.ini
; Auto-generated by scripts/package_rvc_realtime_portable.ps1
; Date: $(Get-Date -Format "yyyy-MM-dd")

[models]
enc=models\\content_encoder.onnx
syn=models\\synthesizer.onnx
index=models\\retrieval.index
rmvpe=models\\rmvpe.onnx

[audio]
cap_id=$CapId
pb_id=$PbId
io_sr=$IoSr

[rvc]
model_sr=$ModelSr
block_sec=$BlockSec
extra_sec=$ExtraSec
crossfade_sec=$CrossfadeSec
prefill_blocks=$PrefillBlocks
index_rate=$IndexRate
up_key=$UpKey
threads=$Threads
noise_scale=$NoiseScale
rms_mix_rate=$RmsMixRate
rmvpe_threshold=$RmvpeThreshold
vad_rms=$VadRms
vad_floor=$VadFloor
max_queue_sec=$MaxQueueSec
"@

Set-Content -Path (Join-Path $outDir "rvc_realtime.ini") -Value $ini -Encoding ASCII

Write-Host "Packaged portable realtime -> $outDir"
Write-Host "Double click: rvc_sdk_ort_realtime.exe (it will auto load rvc_realtime.ini)"
