<#
  Package optimized portable realtime folder with multi-model + dual combo support.
  Reads binaries from build_rvc_sdk_ort/Release*/ and models from E:\RVC_models\.

  Usage:
    powershell -ExecutionPolicy Bypass -File scripts/package_rvc_cpu_optimized.ps1
#>

param(
  [string]$ModelsRoot = "E:\RVC_models",
  [string]$Enc = "E:\RVC_models\test-rvc-onnx\vec-768-layer-12.onnx",
  [string]$Rmvpe = "E:\RVC_models\test-rvc-onnx\rmvpe.onnx",
  [string]$Gtcrn = "E:\Projects\gtcrn\stream\onnx_models\gtcrn_simple.onnx",
  [ValidateSet("cpu", "cuda", "dml")]
  [string]$Runtime = "cpu",
  [int]$PreDenoise = 1,
  [int]$PostDenoise = 1,
  [string]$DefaultProfile = "YaeMiko",
  [string]$OutRoot = "dist_realtime_portable"
)

$ErrorActionPreference = "Stop"

function Ensure-File([string]$Path) {
  if (!(Test-Path -LiteralPath $Path)) { throw "File not found: $Path" }
}

function Ensure-Dir([string]$Path) {
  New-Item -ItemType Directory -Force -Path $Path | Out-Null
}

function Write-ProfileIni {
  param([string]$Path, [string]$Name, [string]$SynFile,
        [int]$ModelSr, [int]$UpKey, [float]$BlockSec, [float]$ExtraSec,
        [string]$Ep = "cpu", [int]$PreDenoise = 1, [int]$PostDenoise = 1)
  $ini = @"
; rvc_realtime.ini
; Auto-generated by scripts/package_rvc_cpu_optimized.ps1
; Date: $(Get-Date -Format "yyyy-MM-dd")

[models]
enc=models\\_shared\\content_encoder.onnx
syn=models\\$Name\\$SynFile
index=models\\$Name\\retrieval.index
rmvpe=models\\_shared\\rmvpe.onnx
gtcrn=models\\_shared\\gtcrn_simple.onnx

[audio]
cap_id=-1
pb_id=-1
io_sr=48000

[rvc]
ep=$Ep
model_sr=$ModelSr
block_sec=$BlockSec
extra_sec=$ExtraSec
crossfade_sec=0.05
prefill_blocks=2
index_rate=0.1
sid=0
up_key=$UpKey
vec_dim=768
threads=8
noise_scale=0.2
rms_mix_rate=0.5
rmvpe_threshold=0.03
vad_rms=0.02
vad_floor=0
max_queue_sec=0.5
pre_denoise=$PreDenoise
post_denoise=$PostDenoise
"@
  Set-Content -Path $Path -Value $ini -Encoding ASCII
}

# Model definitions
$modelDefs = @(
  @{ Name = "YaeMiko";   Stem = "bachongshenzi"; Sr = 40000; UpKey = 6 }
  @{ Name = "啊兰";      Stem = "alan";          Sr = 40000; UpKey = 0 }
  @{ Name = "DuaLive";   Stem = "DUALIVE";       Sr = 48000; UpKey = 0 }
  @{ Name = "mygf-Atri"; Stem = "mygf-Atri";     Sr = 40000; UpKey = 0 }
)

# Combo definitions
$comboDefs = @{
  comboB = @{ Block = 0.35; Extra = 0.35 }
  comboA = @{ Block = 0.30; Extra = 0.30 }
}

# --- Validate inputs ---
Ensure-File $Enc
if ($Rmvpe -ne "") { Ensure-File $Rmvpe }
if ($Gtcrn -ne "") { Ensure-File $Gtcrn }

$buildDir = if ($Runtime -eq "cpu") { "build_rvc_sdk_ort/Release_cpu" } elseif ($Runtime -eq "cuda") { "build_rvc_sdk_ort/Release" } else { "build_rvc_sdk_ort/Release_dml" }
if (!(Test-Path $buildDir)) {
  throw "Build output not found: $buildDir (run scripts/build_rvc_sdk_ort.ps1 first)."
}

$outDir = Join-Path $OutRoot ("win-x64-" + $Runtime + "-optimized")
Ensure-Dir $outDir

# --- Copy binaries ---
foreach ($bin in @("rvc_sdk_ort_realtime.exe","rvc_sdk_ort.dll","rvc_sdk_ort_launcher.exe")) {
  $src = Join-Path $buildDir $bin
  if (Test-Path -LiteralPath $src) { Copy-Item -Force -Path $src -Destination "$outDir/" }
}
foreach ($dll in @("onnxruntime.dll","onnxruntime_providers_cuda.dll","onnxruntime_providers_shared.dll","DirectML.dll","faiss.dll","libblas.dll","liblapack.dll")) {
  $src = Join-Path $buildDir $dll
  if (Test-Path -LiteralPath $src) { Copy-Item -Force -Path $src -Destination "$outDir/" }
}

# --- Copy shared models ---
$modelsDir = Join-Path $outDir "models"
$sharedDir = Join-Path $modelsDir "_shared"
Ensure-Dir $sharedDir
Copy-Item -Force -Path $Enc -Destination (Join-Path $sharedDir "content_encoder.onnx")
if ($Rmvpe -ne "") {
  Copy-Item -Force -Path $Rmvpe -Destination (Join-Path $sharedDir "rmvpe.onnx")
}
if ($Gtcrn -ne "") {
  Copy-Item -Force -Path $Gtcrn -Destination (Join-Path $sharedDir "gtcrn_simple.onnx")
}

$profilesDir = Join-Path $outDir "profiles"
Ensure-Dir $profilesDir

# --- Per-model: copy ONNX + index, generate INI profiles ---
function Pick-Index([string]$dir) {
  $cand = Get-ChildItem -LiteralPath $dir -File -Filter "*.index" |
    Where-Object { $_.Name -match "^added_" } | Sort-Object FullName
  if ($cand) { return ($cand | Select-Object -First 1) }
  $cand2 = Get-ChildItem -LiteralPath $dir -File -Filter "*.index" | Sort-Object FullName
  if ($cand2) { return ($cand2 | Select-Object -First 1) }
  return $null
}

$imported = @()
foreach ($m in $modelDefs) {
  $name = $m.Name
  $srcDir = Join-Path $ModelsRoot $name

  if (!(Test-Path -LiteralPath $srcDir)) {
    Write-Host "SKIP (dir not found): $srcDir"
    continue
  }

  $synB = Join-Path $srcDir "$($m.Stem)_stream_comboB.onnx"
  $synA = Join-Path $srcDir "$($m.Stem)_stream_comboA.onnx"
  if (!(Test-Path -LiteralPath $synB)) {
    Write-Host "SKIP (comboB onnx not found): $synB"
    continue
  }

  $idx = Pick-Index $srcDir
  if ($null -eq $idx) {
    Write-Host "SKIP (no index): $srcDir"
    continue
  }

  # Copy model files
  $dstModel = Join-Path $modelsDir $name
  Ensure-Dir $dstModel
  Copy-Item -Force -Path $synB -Destination (Join-Path $dstModel "synthesizer.onnx")
  if (Test-Path -LiteralPath $synA) {
    Copy-Item -Force -Path $synA -Destination (Join-Path $dstModel "synthesizer_comboA.onnx")
  }
  Copy-Item -Force -Path $idx.FullName -Destination (Join-Path $dstModel "retrieval.index")

  # Combo B profile (default)
  Write-ProfileIni -Path (Join-Path $profilesDir "$name.ini") -Name $name `
    -SynFile "synthesizer.onnx" -ModelSr $m.Sr -UpKey $m.UpKey `
    -BlockSec $comboDefs.comboB.Block -ExtraSec $comboDefs.comboB.Extra `
    -Ep $Runtime -PreDenoise $PreDenoise -PostDenoise $PostDenoise

  # Combo A profile (low-latency)
  if (Test-Path -LiteralPath $synA) {
    Write-ProfileIni -Path (Join-Path $profilesDir "${name}_comboA.ini") -Name $name `
      -SynFile "synthesizer_comboA.onnx" -ModelSr $m.Sr -UpKey $m.UpKey `
      -BlockSec $comboDefs.comboA.Block -ExtraSec $comboDefs.comboA.Extra `
      -Ep $Runtime -PreDenoise $PreDenoise -PostDenoise $PostDenoise
  }

  $imported += $name
  Write-Host "Imported: $name"
}

if ($imported.Count -eq 0) {
  throw "No models imported. Check ModelsRoot and exported ONNX files."
}

# --- Set default rvc_realtime.ini ---
$pick = $DefaultProfile
if (!($imported -contains $pick)) {
  Write-Host "DefaultProfile '$pick' not in imported list, fallback to first."
  $pick = $imported[0]
}
Copy-Item -Force -Path (Join-Path $profilesDir "$pick.ini") `
  -Destination (Join-Path $outDir "rvc_realtime.ini")

Write-Host ""
Write-Host "Done. Packaged -> $outDir"
Write-Host "Imported profiles: $($imported -join ', ')"
Write-Host "Default: $pick (Combo B)"
Write-Host "Launch: rvc_sdk_ort_launcher.exe (GUI) or rvc_sdk_ort_realtime.exe (auto-loads rvc_realtime.ini)"
